# Formation Python
# *Numpy*

Le module **NumPy** offre

- des outils performants pour la manipulation de tableaux à $N$ dimensions,
- des fonctions basiques en algèbre linéaire,
- des fonctions basiques pour les transformées de Fourier,
- des outils pour intégrer du code Fortran,
- des outils pour intégrer du code C/C++,
- des outils d'installation avec support tests unitaires.

# Petite comparaison syntaxique entre Python et Matlab

on veut calculer $u=100\exp\left(-100(x-0.5)^2\right)$ avec $x \in [0,1]$.

**Avec NumPy**

In [1]:
from numpy import *
x = linspace(0., 1., 100)
u = 100.*exp(-100.*(x - .5)**2)

**Avec Matlab**

```
x = linspace(0.,1.,100)
u = 100.*exp(-100.*(x-.5).^2)
```

# Initialisation de tableaux

Il existe différentes façons de créer un tableau en NumPy.

## A partir de sa taille

In [2]:
import numpy as np
np.zeros(4)

array([ 0.,  0.,  0.,  0.])

In [3]:
nx, ny = 2, 2
np.zeros((nx, ny, 2))

array([[[ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.]]])

Il existe également d'autres fonctions: np.ones, np.eye, np.identity, np.empty, ...

Quelques remarques

- Par défaut les éléments créés sont des *float* (équivalent de *double* en C).
- On peut donner un deuxième argument qui précise le type (int, complex, bool, ...).
- Voir également les méthodes dans random.

## Avec une séquence de nombres

In [4]:
np.linspace(-4, 4, 9)

array([-4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [5]:
np.arange(-4, 4, 1)

array([-4, -3, -2, -1,  0,  1,  2,  3])

In [6]:
np.array([1, 2, 3])

array([1, 2, 3])

In [7]:
np.array(range(10))

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
L1, L2 = [1, 2, 3], [4, 5, 6]
np.array([L1, L2])

array([[1, 2, 3],
       [4, 5, 6]])

## A partir d'une fonction

In [9]:
def f(x, y):
    return x**2 + np.sin(y)

np.fromfunction(f, (2, 3))

array([[ 0.        ,  0.84147098,  0.90929743],
       [ 1.        ,  1.84147098,  1.90929743]])

## Avec des objets

In [10]:
class vecteur:
     def __init__(self, x, y, z):
         self.x, self.y, self.z = x, y, z
            
np.array([vecteur(1,1,1), vecteur(2,1,1)])

array([<__main__.vecteur object at 0x7f07ae8ea450>,
       <__main__.vecteur object at 0x7f07ae8ea490>], dtype=object)

## Avec des records

On crée une image contenant $2\times 2$ pixels *rgb*.

In [11]:
img = np.array([[[0, 1], [0, 0]], 
                [[0, 0], [1, 0]],
                [[0, 0], [0, 1]]], dtype=np.float32)
img

array([[[ 0.,  1.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 1.,  0.]],

       [[ 0.,  0.],
        [ 0.,  1.]]], dtype=float32)

On accède au pixel rouge en faisant

In [12]:
img[0]

array([[ 0.,  1.],
       [ 0.,  0.]], dtype=float32)

On accède au pixel en haut à droite en faisant

In [13]:
img[:, 0, 1]

array([ 1.,  0.,  0.], dtype=float32)

On constate que la syntaxe n'est pas très claire et qu'on ne sait pas trop ce qu'on manipule. On va donc mettre des records dans notre tableau pour y voir plus clair.

In [14]:
img = np.array([[(0, 0, 0), (1, 0, 0)], 
                [(0, 1, 0), (0, 0, 1)]], 
                [('r', np.float32), 
                 ('g', np.float32), 
                 ('b', np.float32)])

On peut maintenant accéder à notre pixel rouge en faisant simplement

In [15]:
img['r']

array([[ 0.,  1.],
       [ 0.,  0.]], dtype=float32)

et le pixel en haut à droite s'écrit

In [16]:
img[0, 1]

(1.0, 0.0, 0.0)

# Manipulation de tableaux

Les caractéristiques d'un tableau NumPy $a$ sont les suivantes

- **a.shape**: retourne les dimensions du tableau
- **a.dtype**: retourne le type des éléments du tableau
- **a.size**: retourne le nombre total d'éléments du tableau
- **a.ndim**: retourne la dimension du tableau

In [17]:
a = np.ones((3, 4, 2))
print(a.shape, a.dtype, a.size, a.ndim)

(3, 4, 2) float64 24 3


On peut accéder aux éléments d'un tableau de différentes manières.



<center>
<img src="files/figures/accesElem.png" style="width: 30%;" />
</center>



In [18]:
L1, L2 = [1, -2, 3], [-4, 5, 6]
a = np.array([L1, L2])

In [19]:
a[1, 2]

6

In [20]:
a[:, 1]

array([-2,  5])

In [21]:
a[:, -1:0:-1]

array([[ 3, -2],
       [ 6,  5]])

In [22]:
a[a < 0]

array([-2, -4])

## Redimensionnement d'un tableau

In [23]:
a = np.linspace(1, 10, 10)
a.shape = (2, 5) 

In [24]:
a

array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.]])

In [25]:
a.shape = (a.size,)
print(a)
a.reshape((2, 5))   

[  1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]


array([[  1.,   2.,   3.,   4.,   5.],
       [  6.,   7.,   8.,   9.,  10.]])

**Attention**: *reshape* ne fait pas une copie du tableau mais crée une nouvelle vue.

## Les vues

NumPy crée des tableaux alloués en mémoire selon l'alignement C ou Fortran. 

On peut ensuite y accéder selon différentes vues.  

In [26]:
a = np.linspace(1, 10, 10)

<center>
<img src="files/figures/aView.png" style="width: 40%;" \>
</center>

In [27]:
b = a.reshape((5, 2))

<center>
<img src="files/figures/abView.png" style="width: 40%;" \>
</center>

In [28]:
c = b[:, 0]

<center>
<img src="files/figures/abcView.png" style="width: 40%;" \>
</center>

In [29]:
a[0] = 100

<center>
<img src="files/figures/abcView1.png" style="width: 40%;" \>
</center>

In [30]:
print('-'*5 + 'a' + '-'*5)
print(a)
print('-'*5 + 'b' + '-'*5)
print(b)
print('-'*5 + 'c' + '-'*5)
print(c)

-----a-----
[ 100.    2.    3.    4.    5.    6.    7.    8.    9.   10.]
-----b-----
[[ 100.    2.]
 [   3.    4.]
 [   5.    6.]
 [   7.    8.]
 [   9.   10.]]
-----c-----
[ 100.    3.    5.    7.    9.]


## Copie d'un tableau

In [31]:
a = np.linspace(1, 5, 5)
b = a
c = a.copy()
d = np.zeros(a.shape, a.dtype)
d[:] = a 
b[1] = 9
print('a', a, '\nb', b, '\nc', c, '\nd', d)

a [ 1.  9.  3.  4.  5.] 
b [ 1.  9.  3.  4.  5.] 
c [ 1.  2.  3.  4.  5.] 
d [ 1.  2.  3.  4.  5.]


## Rangement mémoire des tableaux

Il est possible avec NumPy d'avoir un stockage de type C ou de type Fortran.

<center>
<img src="files/figures/storage.png" style="width: 40%;" />
</center>

In [32]:
a = np.array([[1, 2], [3, 4]], order = 'f')
b = np.array([[1, 2], [3, 4]])
print(np.isfortran(a))
print(np.isfortran(b))

True
False


## Boucles sur les tableaux

In [33]:
a = np.zeros((2, 3)) 
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
        a[i, j] = (i + 1)*(j + 1)
print(a)

print('-'*20)

for e in a:
    print(e)

[[ 1.  2.  3.]
 [ 2.  4.  6.]]
--------------------
[ 1.  2.  3.]
[ 2.  4.  6.]


In [34]:
for e in a.flat:
     print(e)

print('-'*20)
        
for index, value in np.ndenumerate(a):
     print(index, value)

1.0
2.0
3.0
2.0
4.0
6.0
--------------------
(0, 0) 1.0
(0, 1) 2.0
(0, 2) 3.0
(1, 0) 2.0
(1, 1) 4.0
(1, 2) 6.0


## Opérations sur les tableaux

- Il n'est pas nécessaire de faire des boucles.
- Python sait faire la différence entre un tableau NumPy et un scalaire.
- Le calcul sur les tableaux se fait via des fonctions C.

Il faut écrire sous forme vectorisée pour avoir les meilleures performances. Pour s'en convaincre, prenons l'exemple suivant:

On veut calculer $b = 3a -1$.

In [35]:
a = np.linspace(0, 1, 1E+06)
b = np.zeros(1E+06)

In [36]:
%timeit  b[:] = 3*a - 1

100 loops, best of 3: 4.82 ms per loop


In [37]:
%timeit for i in range(a.size): b[i] = 3*a[i] - 1

1 loops, best of 3: 544 ms per loop


NumPy fournit un ensemble de fonctions comme $\exp$, $\sin$, ... directement applicable sur des tableaux.

In [38]:
def f(x):
    return np.exp(-x*x)*np.log(1 + x*np.sin(x))

x = np.linspace(0, 1, 1e6)
%timeit a = f(x)

10 loops, best of 3: 68.2 ms per loop


## Broadcasting

<center>
<img src="files/figures/broadcasting.png" style="width: 50%;" />
</center>

In [44]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
print(a)
b = np.array([0, 1, 2])
print(a+b)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [52]:
a = np.arange(0, 40, 10)[:, np.newaxis]
print(a)
print(a+b)

[[ 0]
 [10]
 [20]
 [30]]
[[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [56]:
x, y = np.linspace(0, 1, 11), np.linspace(0, 1, 11)[:, np.newaxis]
print((x-.5)**2 + (y-.5)**2)

[[ 0.5   0.41  0.34  0.29  0.26  0.25  0.26  0.29  0.34  0.41  0.5 ]
 [ 0.41  0.32  0.25  0.2   0.17  0.16  0.17  0.2   0.25  0.32  0.41]
 [ 0.34  0.25  0.18  0.13  0.1   0.09  0.1   0.13  0.18  0.25  0.34]
 [ 0.29  0.2   0.13  0.08  0.05  0.04  0.05  0.08  0.13  0.2   0.29]
 [ 0.26  0.17  0.1   0.05  0.02  0.01  0.02  0.05  0.1   0.17  0.26]
 [ 0.25  0.16  0.09  0.04  0.01  0.    0.01  0.04  0.09  0.16  0.25]
 [ 0.26  0.17  0.1   0.05  0.02  0.01  0.02  0.05  0.1   0.17  0.26]
 [ 0.29  0.2   0.13  0.08  0.05  0.04  0.05  0.08  0.13  0.2   0.29]
 [ 0.34  0.25  0.18  0.13  0.1   0.09  0.1   0.13  0.18  0.25  0.34]
 [ 0.41  0.32  0.25  0.2   0.17  0.16  0.17  0.2   0.25  0.32  0.41]
 [ 0.5   0.41  0.34  0.29  0.26  0.25  0.26  0.29  0.34  0.41  0.5 ]]


## Quelques fonctions utiles

In [39]:
a = np.array([[1, 2, 4], [5, 6, 9]])
print(a)
print(a.flatten())

[[1 2 4]
 [5 6 9]]
[1 2 4 5 6 9]


In [40]:
a, b = np.array([[1, 2], [3, 4]]), array([2, 2])
print(a*b)
print('-'*10)
print(np.dot(a, b))
print('-'*10)
print(np.tensordot(a, b, axes=0))

[[2 4]
 [6 8]]
----------
[ 6 14]
----------
[[[2 2]
  [4 4]]

 [[6 6]
  [8 8]]]


In [41]:
print(np.mgrid[0:2, 0:2])
print('-'*10)
print(np.ogrid[0:2, 0:2])

[[[0 0]
  [1 1]]

 [[0 1]
  [0 1]]]
----------
[array([[0],
       [1]]), array([[0, 1]])]


In [42]:
x, y = np.meshgrid(np.linspace(0, 2, 3), 
                   np.linspace(3, 5, 3))
print(x)
print('-'*10)
print(y)

[[ 0.  1.  2.]
 [ 0.  1.  2.]
 [ 0.  1.  2.]]
----------
[[ 3.  3.  3.]
 [ 4.  4.  4.]
 [ 5.  5.  5.]]


In [43]:
a = np.array([[1, 2, 4], [5, 6, 9]])
print('any', np.any(a > 2))
print('all', np.all(a > 2))
print( 'where 1', np.where(a <= 1))
print( 'where 2', np.where(a > 1))

any True
all False
where 1 (array([0]), array([0]))
where 2 (array([0, 0, 1, 1, 1]), array([1, 2, 0, 1, 2]))


## Autres opérations sur un tableau

- ```a.argmax```: renvoie un tableau d'indices des valeurs maximales selon un axe
- ```a.max```: renvoie le maximum
- ```a.astype```: renvoie un tableau de a convertit sous un certain type
- ```a.conj```: renvoie le conjugué de a
- ```a.sum```: renvoie la somme des éléments de a
- ```a.prod```: renvoie le produit des éléments de a
- ```a.transpose```: renvoie la transposé de a

# Les entrées-sorties

Il existe différentes manières de sauvegarder ses données 

- formats NumPy
- pickle
- HDF5, NetCDF, VTK, ...

On s'intéressera ici uniquement aux formats fournis par NumPy.

## load et save

In [45]:
np.save('/tmp/123', np.array([[1, 2, 3], [4, 5, 6]]))
np.load('/tmp/123.npy')

array([[1, 2, 3],
       [4, 5, 6]])

## load et savez

In [46]:
x = np.linspace(0, 2*np.pi, 10)
y = np.sin(x)   
np.savez('/tmp/sin', x1=x, y1=y)
t = np.load('/tmp/sin.npz')
print(t.files)
print(t['x1'])

['y1', 'x1']
[ 0.          0.6981317   1.3962634   2.0943951   2.7925268   3.4906585
  4.1887902   4.88692191  5.58505361  6.28318531]


## loadtxt

In [47]:
from io import StringIO
c = StringIO("0 1\n2 3")
print(np.loadtxt(c))

c = StringIO("1,0,2\n3,0,4")
x, y = np.loadtxt(c, delimiter=',', usecols=(0, 2),
                  unpack=True)
print(x)

[[ 0.  1.]
 [ 2.  3.]]
[ 1.  3.]


## savetxt

In [48]:
x = y = z = np.arange(0.0, 5.0, 1.0)

np.savetxt('test.out', x, delimiter=',')
!cat 'test.out'
print('-'*10)

np.savetxt('test.out', (x, y, z)) 
!cat 'test.out'
print('-'*10)

np.savetxt('test.out', x, fmt='%1.4e')
!cat 'test.out'

0.000000000000000000e+00
1.000000000000000000e+00
2.000000000000000000e+00
3.000000000000000000e+00
4.000000000000000000e+00
----------
0.000000000000000000e+00 1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00 4.000000000000000000e+00
0.000000000000000000e+00 1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00 4.000000000000000000e+00
0.000000000000000000e+00 1.000000000000000000e+00 2.000000000000000000e+00 3.000000000000000000e+00 4.000000000000000000e+00
----------
0.0000e+00
1.0000e+00
2.0000e+00
3.0000e+00
4.0000e+00


*Remarque*: tous les exemples d'entrées-sorties ont été pris dans le guide de référence de numpy (voir [ici](http://docs.scipy.org/doc/numpy/reference/routines.io.html)).

## Options pour l'affichage des tableaux

In [49]:
a  = np.sin(np.arange(3))
print(a)

[ 0.          0.84147098  0.90929743]


In [50]:
import sys
np.set_printoptions(precision=2, threshold=sys.maxsize)
print(a)

[ 0.    0.84  0.91]
